from typing import Protocol

from .models import DividendEvent, ResolvedPortfolio


class PortfolioDataSource(Protocol):
    def get_resolved_portfolio(self) -> ResolvedPortfolio: ...
    def get_symbol_dividends(self, isin: str) -> list[DividendEvent]: ...
    def is_portfolio_cached(self) -> bool: ...
    def clear_cache(self) -> None: ...
